# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renewal.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Setting_window(QtWidgets.QDialog):
    # def __init__(self):
    #     self.setupUI()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Setting")
        Dialog.resize(400, 100)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(230, 40, 121, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 40, 181, 16))
        font = QtGui.QFont()
        font.setFamily("서울남산 장체B")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox.setItemText(0, _translate("Dialog", "영어(English)"))
        self.comboBox.setItemText(1, _translate("Dialog", "한국어(Korean)"))
        self.label.setText(_translate("Dialog", "언어 선택(Language Selection)"))

class Grabber(QtWidgets.QWidget):
    def __init__(self):
        super(Grabber, self).__init__()
        # self.showMaximized()
        self.setGeometry(0, 0, 1920, 1080)
        self.setWindowTitle('Screen grabber')
        # ensure that the widget always stays on top, no matter what
        self.setWindowFlags(self.windowFlags() | QtCore.Qt.FramelessWindowHint) # | QtCore.Qt.WindowStaysOnTopHint)
        layout = QtWidgets.QVBoxLayout()

        self.setLayout(layout)
        # limit widget AND layout margins
        layout.setGeometry(QtCore.QRect(0,0,1328, 147))
        layout.setContentsMargins(0, 0, 0, 0) # left, top, right, bottom
        self.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        # create a "placeholder" widget for the screen grab geometry
        self.grabWidget = QtWidgets.QWidget()
        # self.grabWidget.setGeometry(0, 0, 100, 100)
        self.grabWidget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        layout.addWidget(self.grabWidget)

        # let's add a configuration panel
        self.panel = QtWidgets.QWidget()
        layout.addWidget(self.panel)

        panelLayout = QtWidgets.QHBoxLayout()
        self.panel.setLayout(panelLayout)
        panelLayout.setContentsMargins(0, 0, 0, 0) # 틀 너비 바꾸는 느낌
        self.setContentsMargins(0, 0, 0, 0)

        # self.configButton = QtWidgets.QPushButton(self.style().standardIcon(QtWidgets.QStyle.SP_ComputerIcon), '')
        # self.configButton.setFlat(True)
        # panelLayout.addWidget(self.configButton)

        # panelLayout.addWidget(VLine())

        # self.fpsSpinBox = QtWidgets.QSpinBox()
        # panelLayout.addWidget(self.fpsSpinBox)
        # self.fpsSpinBox.setRange(1, 50)
        # self.fpsSpinBox.setValue(15)
        # panelLayout.addWidget(QtWidgets.QLabel('fps'))

        # panelLayout.addWidget(VLine())

        self.widthLabel = QtWidgets.QLabel()
        # panelLayout.addWidget(self.widthLabel)
        self.widthLabel.setFrameShape(QtWidgets.QLabel.StyledPanel|QtWidgets.QLabel.Sunken)

        # panelLayout.addWidget(QtWidgets.QLabel('x'))

        self.heightLabel = QtWidgets.QLabel()
        # panelLayout.addWidget(self.heightLabel)
        self.heightLabel.setFrameShape(QtWidgets.QLabel.StyledPanel|QtWidgets.QLabel.Sunken)

        # panelLayout.addWidget(QtWidgets.QLabel('px'))
        #
        # panelLayout.addWidget(VLine())

        # self.recButton = QtWidgets.QPushButton('rec')
        # panelLayout.addWidget(self.recButton)
        #
        # self.playButton = QtWidgets.QPushButton('play')
        # panelLayout.addWidget(self.playButton)

        # panelLayout.addStretch(0)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setStyleSheet("background-color : #EDECEA;")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 341, 41))
        font = QtGui.QFont()
        font.setFamily("서울남산 장체B")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color : #C4BCB8;")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 190, 200, 120))
        self.pushButton.setStyleSheet(
            '''
            QPushButton{image:url(./Image/1-1 copy.png); border:0px;}
            QPushButton:hover{image:url(./Image/1-3 copy.png); border:0px;}
            QPushButton:checked{image:url(./Image/1-2 copy.png); border:0px;}
            ''')
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 190, 200, 120))
        self.pushButton_2.setStyleSheet(
            '''
            QPushButton{image:url(./image/3-1 copy.png); border:0px;}
            QPushButton:hover{image:url(./image/3-3 copy.png); border:0px;}
            QPushButton:checked{image:url(./image/3-2 copy.png); border:0px;}
            ''')
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setCheckable(True)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 370, 200, 120))
        self.pushButton_3.setStyleSheet(
            '''
            QPushButton{image:url(./Image/2-1 copy.png); border:0px;}
            QPushButton:hover{image:url(./Image/2-3 copy.png); border:0px;}
            QPushButton:checked{image:url(./Image/2-2 copy.png); border:0px;}
            ''')
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 370, 200, 120))
        self.pushButton_4.setStyleSheet(
            '''
            QPushButton{image:url(./Image/4-1 copy.png); border:0px;}
            QPushButton:hover{image:url(./Image/4-3 copy.png); border:0px;}
            QPushButton:checked{image:url(./Image/4-2 copy.png); border:0px;}
            ''')
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 560, 201, 201))
        self.pushButton_5.setStyleSheet("border-radius : 100; border : 2px;")
        self.pushButton_5.setStyleSheet(
            '''
            QPushButton{image:url(./Image/Power.png); border:0px;}
            QPushButton:hover{image:url(./Image/Power-hover.png); border:0px;}
            QPushButton:checked{image:url(./Image/Power-on.png); border:0px;}
            ''')
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setCheckable(True)
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 650, 111, 111))
        self.pushButton_6.setStyleSheet("border-radius : 55; border : 2px;")
        self.pushButton_6.setStyleSheet(
            '''
            QPushButton{image:url(./Image/qmark.png); border:0px;}
            QPushButton:hover{image:url(./Image/qmark-hover.png); border:0px;}
            ''')
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(380, 650, 111, 111))
        self.pushButton_7.setStyleSheet("border-radius : 55; border : 2px;")
        self.pushButton_7.setStyleSheet(
            '''
            QPushButton{image:url(./Image/cam.png); border:0px;}
            QPushButton:hover{image:url(./Image/cam-hover.png); border:0px;}
            ''')
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(430, 80, 51, 51))
        self.pushButton_8.setStyleSheet("border-radius : 25;")
        self.pushButton_8.setStyleSheet(
            '''
            QPushButton{image:url(./Image/setting.png); border:0px;}
            QPushButton:hover{image:url(./Image/setting-hover.png); border:0px;}
            ''')
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.settingwindow)
        self.pushButton_9= QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 860, 480, 131))
        self.pushButton_9.setStyleSheet(
            '''
            QPushButton{image:url(./Image/inbody.png); border:0px;}
            QPushButton:hover{image:url(./Image/인바디.png); border:0px;}
            ''')
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(370, 90, 56, 41))
        font = QtGui.QFont()
        font.setFamily("서울남산 장체B")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color : #ACCCC4;")
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(350, 340, 130, 16))
        self.line_2.setStyleSheet("color : #C4BCB8;")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(10)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(530, 62, 1328, 747))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color : #C6DFD6;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(166, 0, 996, 747))
        self.label_6.setStyleSheet("background-color : white;")
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 52, 271, 41))
        font = QtGui.QFont()
        font.setFamily("서울남산 장체B")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("color : #ACCCC4")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(40, 340, 130, 16))
        self.line.setStyleSheet("color : #C4BCB8;")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(250, 220, 20, 100))
        self.line_3.setStyleSheet("color : #C4BCB8;")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(10)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(250, 376, 20, 100))
        self.line_4.setStyleSheet("color : #C4BCB8;")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(10)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(210, 320, 100, 56))
        font = QtGui.QFont()
        font.setFamily("서울남산 장체B")
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LayoutDirectionAuto)
        self.label_4.setStyleSheet("color : #ACCCC4;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def settingwindow(self):
        dlg = Setting_window()
        dlg.setupUi(dlg)
        dlg.exec_()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Presentation Tool"))
        self.label_3.setText(_translate("Form", "1.0"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label.setText(_translate("Form", "Hand Gesture"))
        self.label_4.setText(_translate("Form", "MODE"))

    def updateMask(self):
        # get the *whole* window geometry, including its titlebar and borders
        frameRect = self.frameGeometry()
        print(frameRect)
        # get the grabWidget geometry and remap it to global coordinates
        grabGeometry = self.grabWidget.geometry()
        grabGeometry = QtCore.QRect(0, 0, 1328, 147)
        grabGeometry.moveTopLeft(self.grabWidget.mapToGlobal(QtCore.QPoint(530, 871)))

        # get the actual margins between the grabWidget and the window margins
        left = frameRect.left() - grabGeometry.left()
        top = frameRect.top() - grabGeometry.top()
        right = frameRect.right() - grabGeometry.right()
        bottom = frameRect.bottom() - grabGeometry.bottom()


        # reset the geometries to get "0-point" rectangles for the mask
        frameRect.moveTopLeft(QtCore.QPoint(530, 871))
        grabGeometry.moveTopLeft(QtCore.QPoint(530, 871))

        # create the base mask region, adjusted to the margins between the
        # grabWidget and the window as computed above
        region = QtGui.QRegion(frameRect.adjusted(left, top, right, bottom))

        # "subtract" the grabWidget rectangle to get a mask that only contains
        # the window titlebar, margins and panel
        region -= QtGui.QRegion(grabGeometry)
        self.setMask(region)

        # update the grab size according to grabWidget geometry
        self.widthLabel.setText(str(self.grabWidget.width()))
        self.heightLabel.setText(str(self.grabWidget.height()))

    # def resizeEvent(self, event):
    #     super(Grabber, self).resizeEvent(event)
    #     # the first resizeEvent is called *before* any first-time showEvent and
    #     # paintEvent, there's no need to update the mask until then; see below


    def paintEvent(self, event):
        super(Grabber, self).paintEvent(event)
        # on Linux the frameGeometry is actually updated "sometime" after show()
        # is called; on Windows and MacOS it *should* happen as soon as the first
        # non-spontaneous showEvent is called (programmatically called: showEvent
        # is also called whenever a window is restored after it has been
        # minimized); we can assume that all that has already happened as soon as
        # the first paintEvent is called; before then the window is flagged as
        # "dirty", meaning that there's no need to update its mask yet.
        # Once paintEvent has been called the first time, the geometries should
        # have been already updated, we can mark the geometries "clean" and then
        # actually apply the mask.


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    #ui = Ui_Form()
    #ui.setupUi(Form)
    #Form.show()
    grabber = Grabber()
    grabber.setupUi(grabber)
    grabber.show()
    sys.exit(app.exec_())
